### ISSUE TITLE
Error encountered when running cron job

### ISSUE THREAD

**Issue by baojd42** [Jeadie/notion-rss#7]
When fetch resources from the a RSS source, I got en error and it reads "body.properties.Description.rich_text[0].text.content.length should be ≤ `2000`, instead was `7963`".

Why this error occured?

Is there a place to config the content.length to be a larger number?

The RSS source is https://[celery.school/rss.xml](https://celery.school/rss.xml)

Many thanks to your help.

**Comment by Jeadie** [comment]
Hi @baojd42 , this appears to be an issue/error coming directly from Notion.io. The error seems to be because we add the full description into a single rich_text object, [link](https://github.com/Jeadie/notion-rss/blob/main/notion_dao.go#L224-L233). It may be possible to paginate the description, but will need to verify.
